language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
script:
  - travis_wait sudo sh -c "ulimit -n 795197 && exec sudo -u travis bash -c 'source $HOME/otp/18.1/activate && MODE=state_based ulimit'"
  - travis_wait sudo sh -c "ulimit -n 795197 && exec sudo -u travis bash -c 'source $HOME/otp/18.1/activate && MODE=state_based make ct'"
  - travis_wait sudo sh -c "ulimit -n 795197 && exec sudo -u travis bash -c 'source $HOME/otp/18.1/activate && MODE=delta_based make ct'"
  - make test
  - make xref
  - make dialyzer
  - make lint
  - MODE=state_based make ct
  - MODE=delta_based make ct
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: required
