language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
script:
  - make xref
  - make dialyzer
  - make lint
  - make eunit
  - MODE=state_based make ct
  - MODE=delta_based make ct
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: required
env:
  global:
    - OMIT_HIGH_ULIMIT=true
