language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
  - pip install codecov
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
  - MODE=state_based make ct
  - MODE=delta_based make ct
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false
after_success: codecov
