language: erlang
otp_release:
  - 18.1
  - 17.4
  - R16B03
script:
  - make
  - make test
  - make xref
  - make dialyzer
notifications:
  email: christopher.meiklejohn@gmail.com
  irc: "irc.freenode.org#lasp-lang"
sudo: false
