language: erlang
otp_release:
  - 18.0
  - 17.4
  - R16B03
  - R16B02
  - R16B01
script:
  - make dialyzer
  - make xref
  - make
  - make test
  - make riak-test
notifications:
  email: christopher.meiklejohn@gmail.com
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git
